namespace Lane.Audio.Voiceprints;

/// <summary>
/// Turns speech into the 80-band log-mel features a speaker-embedding model expects.
///
/// This is Kaldi's <c>fbank</c>, reimplemented rather than depended on, and it is worth
/// being explicit about why the constants below are not adjustable. They are not tuning
/// knobs; they are half of a contract with a model whose other half was trained in Python.
/// A window a millisecond wide, a mel range that stops at 7600 instead of 8000, a window
/// function that is Hann where Kaldi's is Hann raised to 0.85 — none of those crash, and
/// none of them show up as an error. They show up as a speaker-recognition rate that is
/// merely disappointing, which is indistinguishable from the model being mediocre.
///
/// So the numbers here are Kaldi's defaults as WeSpeaker invokes them, and the tests check
/// the output against features generated by that same Python, band for band.
///
/// Samples are taken at 16-bit scale rather than normalised to ±1, because that is what
/// Kaldi does and what the model was trained on. It happens not to matter — a constant scale
/// is a constant offset in the log domain, which the per-utterance mean subtraction at the
/// end removes exactly — but matching is cheaper than reasoning about it every time.
/// </summary>
internal static class FilterBank
{
    public const int MelBins = 80;

    private const int SampleRate  = 16000;
    private const int FrameLength = 400;               // 25 ms
    private const int FrameShift  = 160;               // 10 ms
    private const int FftSize     = 512;               // the next power of two above a frame
    private const int Spectrum    = FftSize / 2 + 1;

    private const float PreEmphasis   = 0.97f;
    private const float LowFrequency  = 20f;
    private const float HighFrequency = SampleRate / 2f;

    /// <summary>
    /// Kaldi floors a silent band rather than taking the log of nothing.
    ///
    /// This is C++'s <c>numeric_limits&lt;float&gt;::epsilon()</c> — the gap between 1 and the
    /// next float — and deliberately not C#'s <c>float.Epsilon</c>, which is the smallest
    /// denormal and some thirty-eight orders of magnitude smaller. Same name, different
    /// number, and the wrong one turns every silent frame into an outlier that drags the
    /// utterance mean with it.
    /// </summary>
    private const float EnergyFloor = 1.19209290e-7f;

    private static readonly float[] Window = BuildWindow();

    private static readonly Filter[] Filters = BuildFilters();

    /// <summary>One triangular mel band: where it starts in the spectrum, and its weights.</summary>
    private readonly record struct Filter(int Start, float[] Weights);

    public static int FrameCount(int samples) =>
        samples < FrameLength ? 0 : 1 + (samples - FrameLength) / FrameShift;

    /// <summary>
    /// Features for one utterance, laid out frame after frame as the model wants them:
    /// <c>[frames * 80]</c>, ready to become a <c>[1, frames, 80]</c> tensor.
    ///
    /// Mean-normalised over time, which is the step that makes a voiceprint about the voice
    /// rather than about the microphone and the room it was recorded in.
    /// </summary>
    public static float[] Compute(ReadOnlySpan<byte> pcm16)
    {
        int samples = pcm16.Length / 2;
        int frames  = FrameCount(samples);

        if (frames == 0) return [];

        float[] features = new float[frames * MelBins];

        float[] frame    = new float[FftSize];
        float[] imaginary = new float[FftSize];
        float[] power    = new float[Spectrum];

        for (int f = 0; f < frames; f++)
        {
            Array.Clear(frame);
            Array.Clear(imaginary);

            Extract(pcm16, f * FrameShift, frame);
            PowerSpectrum(frame, imaginary, power);

            Span<float> bands = features.AsSpan(f * MelBins, MelBins);

            for (int m = 0; m < MelBins; m++)
            {
                Filter filter = Filters[m];

                float energy = 0f;

                for (int k = 0; k < filter.Weights.Length; k++)
                    energy += power[filter.Start + k] * filter.Weights[k];

                bands[m] = MathF.Log(MathF.Max(energy, EnergyFloor));
            }
        }

        SubtractMean(features, frames);

        return features;
    }

    /// <summary>
    /// One window of samples, prepared the way Kaldi prepares it: DC removed, pre-emphasis
    /// applied, then the window function. The order matters — pre-emphasising after the
    /// window would emphasise the window's own edges.
    /// </summary>
    private static void Extract(ReadOnlySpan<byte> pcm16, int from, Span<float> into)
    {
        float sum = 0f;

        for (int i = 0; i < FrameLength; i++)
        {
            short sample = BitConverter.ToInt16(pcm16[((from + i) * 2)..]);

            into[i] = sample;
            sum += sample;
        }

        float mean = sum / FrameLength;

        for (int i = 0; i < FrameLength; i++) into[i] -= mean;

        // Backwards, so each sample is emphasised against the original value of the one
        // before it rather than against an already-emphasised one. The first sample has no
        // predecessor and uses itself, which is what Kaldi does.
        for (int i = FrameLength - 1; i > 0; i--) into[i] -= PreEmphasis * into[i - 1];

        into[0] -= PreEmphasis * into[0];

        for (int i = 0; i < FrameLength; i++) into[i] *= Window[i];
    }

    private static void PowerSpectrum(float[] real, float[] imaginary, Span<float> power)
    {
        Fft(real, imaginary);

        for (int k = 0; k < Spectrum; k++)
            power[k] = real[k] * real[k] + imaginary[k] * imaginary[k];
    }

    /// <summary>
    /// In-place radix-2 FFT. Hand-rolled for the same reason the resampler beside it is:
    /// one 512-point transform is sixty lines and a test, against a numerics package whose
    /// version would then have to agree with a model file forever.
    /// </summary>
    private static void Fft(float[] real, float[] imaginary)
    {
        int n = real.Length;

        // Bit-reversal permutation.
        for (int i = 1, j = 0; i < n; i++)
        {
            int bit = n >> 1;

            for (; (j & bit) != 0; bit >>= 1) j ^= bit;

            j ^= bit;

            if (i < j)
            {
                (real[i], real[j]) = (real[j], real[i]);
                (imaginary[i], imaginary[j]) = (imaginary[j], imaginary[i]);
            }
        }

        for (int length = 2; length <= n; length <<= 1)
        {
            int half = length / 2;

            for (int i = 0; i < n; i += length)
            {
                for (int j = 0; j < half; j++)
                {
                    // Read from a table rather than walking a rotation round the circle by
                    // repeated multiplication. The walk is the textbook form and it drifts:
                    // 256 single-precision complex multiplies accumulate enough error to
                    // move a quiet mel band by a hundredth of a log unit, which is small
                    // enough to look like the model rather than like a bug.
                    (float wReal, float wImaginary) = Twiddles[half + j];

                    int a = i + j;
                    int b = a + half;

                    float bReal = real[b] * wReal - imaginary[b] * wImaginary;
                    float bImaginary = real[b] * wImaginary + imaginary[b] * wReal;

                    real[b] = real[a] - bReal;
                    imaginary[b] = imaginary[a] - bImaginary;

                    real[a] += bReal;
                    imaginary[a] += bImaginary;
                }
            }
        }
    }

    /// <summary>
    /// Every root of unity the transform needs, laid out so stage <c>half</c> reads from
    /// <c>Twiddles[half + j]</c>. Each is computed straight from its own angle in double
    /// precision, so none of them carries error from the one before it.
    /// </summary>
    private static readonly (float Real, float Imaginary)[] Twiddles = BuildTwiddles();

    private static (float Real, float Imaginary)[] BuildTwiddles()
    {
        (float, float)[] twiddles = new (float, float)[FftSize];

        for (int half = 1; half < FftSize; half <<= 1)
        {
            for (int j = 0; j < half; j++)
            {
                double angle = -Math.PI * j / half;

                twiddles[half + j] = ((float)Math.Cos(angle), (float)Math.Sin(angle));
            }
        }

        return twiddles;
    }

    /// <summary>
    /// Per-utterance mean subtraction, band by band across time.
    ///
    /// What it removes is everything constant about the recording — the microphone's
    /// response, the room, the gain — leaving what varies, which is the speaking. Without it
    /// a voiceprint recognises the microphone as much as the person, and the same person on
    /// a different device stops matching themselves.
    /// </summary>
    private static void SubtractMean(float[] features, int frames)
    {
        for (int m = 0; m < MelBins; m++)
        {
            float sum = 0f;

            for (int f = 0; f < frames; f++) sum += features[f * MelBins + m];

            float mean = sum / frames;

            for (int f = 0; f < frames; f++) features[f * MelBins + m] -= mean;
        }
    }

    /// <summary>Kaldi's "povey" window: Hann, raised to 0.85.</summary>
    private static float[] BuildWindow()
    {
        float[] window = new float[FrameLength];

        for (int i = 0; i < FrameLength; i++)
        {
            double hann = 0.5 - 0.5 * Math.Cos(2 * Math.PI * i / (FrameLength - 1));

            window[i] = (float)Math.Pow(hann, 0.85);
        }

        return window;
    }

    /// <summary>
    /// The triangular mel bands, evenly spaced on the mel scale and overlapping by half.
    /// Built once: they depend only on constants.
    /// </summary>
    private static Filter[] BuildFilters()
    {
        double lowMel  = ToMel(LowFrequency);
        double highMel = ToMel(HighFrequency);
        double step    = (highMel - lowMel) / (MelBins + 1);

        double binWidth = (double)SampleRate / FftSize;

        Filter[] filters = new Filter[MelBins];

        for (int m = 0; m < MelBins; m++)
        {
            double left   = lowMel + m * step;
            double centre = left + step;
            double right  = left + 2 * step;

            int start = -1;

            List<float> weights = [];

            for (int k = 0; k < Spectrum; k++)
            {
                double mel = ToMel(binWidth * k);

                if (mel <= left || mel >= right) continue;

                float weight = (float)(mel <= centre
                    ? (mel - left) / (centre - left)
                    : (right - mel) / (right - centre));

                if (start < 0) start = k;

                weights.Add(weight);
            }

            filters[m] = new Filter(Math.Max(start, 0), [.. weights]);
        }

        return filters;
    }

    private static double ToMel(double hertz) => 1127.0 * Math.Log(1.0 + hertz / 700.0);
}
