<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lane.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="ElevenLabs-DotNet" Version="3.7.2" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.48.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="SoundTouch.Net" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Lane.Core/Lane.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lane.Tests" />
  </ItemGroup>

</Project>
